#!/usr/bin/sh

brightness1=0.7
brightness2=1
leftDisplay="DisplayPort-2"
rightDisplay="HDMI-A-0"

toggle_rotation() {
    currentOrientation=`(xrandr | sed -n '/\bconnected\b/p' | grep -v primary | awk '{print $4}')`

    if [[ $currentOrientation = "left" ]]; then
        set_landscape
    elif [[ $currentOrientation = "(normal" ]]; then
        set_portrait
    fi
}

set_landscape() {
    xrandr --output "$leftDisplay" --mode 1920x1080 --pos 0x0 --rotate normal --primary --rate 144.00 --brightness $brightness1 --output "$rightDisplay" --mode 1920x1080 --pos 1920x0 --rotate normal --brightness $brightness2

    wallpaper-engine &
}

set_portrait() {
    xrandr --output "$leftDisplay" --mode 1920x1080 --pos 0x0 --rotate normal --primary --rate 144.00 --brightness $brightness1 --output "$rightDisplay" --mode 1920x1080 --pos 1920x0 --rotate left --brightness $brightness2

    wallpaper-engine &
}



if [[ -n $1 ]]; then
    if [[ $1 = "--toggle" ]]; then
        toggle_rotation
    elif [[ $1 = "--set" ]]; then
        if [[ $2 = "landscape" ]]; then
            set_landscape
        elif [[ $2 = "portrait" ]]; then
            set_portrait
        fi
    fi
fi
