#!/bin/sh
# Toggle Spotify's play
play_pause() {
	dbus-send --print-reply --dest=org.mpris.MediaPlayer2.ncspot /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.PlayPause
}

# Switches to spotify's next music
next() {
	dbus-send --print-reply --dest=org.mpris.MediaPlayer2.ncspot /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Next
}

# Execute accordingly
if [[ "$1" == "--play-pause" ]]; then
	play_pause
elif [[ "$1" == "--next" ]]; then
	next
fi
