#!/bin/bash

#A script for setting video backgrounds using xwinwrap and mpv
export DISPLAY=":0"

landscapepath="/home/$USER/Videos/wallpapers/landscape"
portraitpath="/home/$USER/Videos/wallpapers/portrait"

monitorgeometry="$(xrandr --listactivemonitors | sed -n '2,3p' | awk '{print $3}' | awk -F'(/|x|+)' '{printf("%sx%s+%s+%s", $1, $3, $5, $6); print ""}')"
g1="$(echo "$monitorgeometry" | head -n 1)"
g2="$(echo "$monitorgeometry" | tail -n 1)"

ori="$(echo "$g2" | cut -c -4)"
if [ "$ori" = "1920" ]; then
    ORIENTATION="landscape"
elif [ "$ori" = "1080" ]; then
    ORIENTATION="portrait"
else
    ORIENTATION="landscape"
fi    

videos="$(ls -1p $landscapepath | grep -v / | sort -R)"
v1="$(echo "$videos" | head -n 1)"

if [ "$ORIENTATION" = "landscape" ]; then
    path="$landscapepath"
    v2="$(echo "$videos" | tail -n 1)"
else
    path="$portraitpath"
    v2="$(ls -1p $portraitpath | grep -v / | sort -R | head -n 1)"
fi

echo "$landscapepath/$v1"
echo "$path/$v2"

killall xwinwrap

xwinwrap -g "$g1" -ni -s -st -sp -b -nf -ov -- mpv --profile=wallpaper -wid WID "$landscapepath/$v1" &
xwinwrap -g "$g2" -ni -s -st -sp -b -nf -ov -- mpv --profile=wallpaper -wid WID "$path/$v2" &
