- lineinfile:
     path: /etc/sudoers.d/quatro-allow-to-makepkg
     state: present
     line: "quatro ALL=(ALL) NOPASSWD: /usr/bin/pacman"
     validate: /usr/sbin/visudo -cf %s
     create: yes

- name: users | quatro | create .ssh directory
  tags: dotfiles,quatro,ssh,users
  file:
    path: "{{ item.dir }}"
    state: directory
    owner: quatro
    group: quatro
    mode: 0700
  with_items:
    - { dir: '/home/quatro/.ssh' }

- name: users | quatro | create config directories
  tags: dotfiles,quatro,tmux,users,vim,zsh
  file:
    path: /home/quatro/{{ item.dir }}
    state: directory
    owner: quatro
    group: quatro
    mode: 0700
  with_items:
    - { dir: '.config' }
    - { dir: '.config/nvim' }
    - { dir: '.config/nvim/lua' }
    - { dir: '.config/nvim/lua/user' }
    - { dir: '.config/mpv' }
    - { dir: 'scripts' }
    - { dir: 'pjx' }
    - { dir: 'Videos' }
    - { dir: 'Videos/wallpapers' }
    - { dir: 'Videos/wallpapers/landscape' }
    - { dir: 'Videos/wallpapers/portrait' }

- name: users | quatro | copy dotfiles
  tags: dotfiles,users,quatro,users,vim,zsh
  copy:
    src: users/quatro/{{ item.src }}
    dest: /home/quatro/{{ item.dest }}
    owner: quatro
    group: quatro
    mode: 0755
  with_items:
    - { src: 'ssh', dest: '.ssh' }
    - { src: 'config/fastfetch', dest: '.config' }
    - { src: 'config/hypr', dest: '.config' }
    - { src: 'config/kitty', dest: '.config' }
    - { src: 'config/mako', dest: '.config' }
    - { src: 'config/mimeapps.list', dest: '.config' }
    - { src: 'config/mpv', dest: '.config' }
    - { src: 'config/nvim/lua/user', dest: '.config/nvim/lua' }
    - { src: 'config/starship.toml', dest: '.config' }
    - { src: 'config/swaylock', dest: '.config' }
    - { src: 'config/waybar', dest: '.config' }
    - { src: 'config/wofi', dest: '.config' }
    - { src: 'config/gtk-3.0', dest: '.config' }
    - { src: 'config/xsettingsd', dest: '.config' }
    - { src: 'gtkrc-2.0', dest: '.gtkrc-2.0' }
    - { src: 'XCompose', dest: '.XCompose' }
    - { src: 'zshrc', dest: '.zshrc' }
    - { src: 'bashrc', dest: '.bashrc' }
    - { src: 'usr/local/bin/compiler', dest: 'scripts/compiler' }
    - { src: 'usr/local/bin/opout', dest: 'scripts/opout' }
    - { src: 'scripts/rotate-screen', dest: 'scripts/rotate-screen' }
    - { src: 'scripts/wallpaper-engine', dest: 'scripts/wallpaper-engine' }
    - { src: 'scripts/wallhelper', dest: 'scripts/wallhelper' }
    - { src: 'scripts/switch-audio', dest: 'scripts/switch-audio' }
    - { src: 'scripts/project-finder', dest: 'scripts/project-finder' }
    - { src: 'scripts/project-terminals', dest: 'scripts/project-terminals' }
    - { src: 'pjx/project-terminals.txt', dest: 'pjx/project-terminals.txt' }
