- name: users | quatro | create 'me' group
  tags: groups,quatro,users
  group:
    name: me
    state: present

- name: users | quatro | create user
  tags: quatro,sudo,users
  user:
    name: quatro
    group: quatro
    groups: me,{{ sudo_group }}
    state: present
    comment: ""
    password: ""
    shell: /bin/zsh


- lineinfile:
     path: /etc/sudoers.d/quatro-allow-to-makepkg
     state: present
     line: "quatro ALL=(ALL) NOPASSWD: /usr/bin/pacman"
     validate: /usr/sbin/visudo -cf %s
     create: yes

- name: users | quatro | add sudoers file
  tags: quatro,settings,simone,sudo,system,users
  copy:
    src: users/sudoers_quatro
    dest: /etc/sudoers.d/quatro
    owner: root
    group: root
    mode: 0440

- name: users | quatro | create .ssh directory
  tags: dotfiles,quatro,ssh,users
  file:
    path: "{{ item.dir }}"
    state: directory
    owner: quatro
    group: quatro
    mode: 0700
  with_items:
    - { dir: '/home/quatro/.ssh' }

- name: users | quatro | add public key
  tags: dotfiles,quatro,ssh,ssh-keys,users
  authorized_key:
    user: quatro
    key: "{{ item }}"
  with_file:
    - users/quatro/ssh/quatro_id_ed25519.pub

- name: users | quatro | create config directories
  tags: dotfiles,quatro,tmux,users,vim,zsh
  file:
    path: /home/quatro/{{ item.dir }}
    state: directory
    owner: quatro
    group: quatro
    mode: 0700
  with_items:
    - { dir: '.config' }
    - { dir: '.config/nvim' }
    - { dir: '.config/nvim/lua' }
    - { dir: '.config/nvim/lua/user' }
    - { dir: '.config/mpv' }
    - { dir: 'scripts' }
    - { dir: 'pjx' }

- name: users | quatro | copy dotfiles
  tags: dotfiles,users,quatro,users,vim,zsh
  copy:
    src: users/quatro/{{ item.src }}
    dest: /home/quatro/{{ item.dest }}
    owner: quatro
    group: quatro
    mode: 0755
  with_items:
    - { src: 'config/nvim/lua/user', dest: '.config/nvim/lua' }
    - { src: 'config/mpv', dest: '.config' }
    - { src: 'scripts/archcraft', dest: 'scripts' }
    - { src: 'zshrc', dest: '.zshrc' }
    - { src: 'xinitrc', dest: '.xinitrc' }
    - { src: 'inputrc', dest: '.inputrc' }
    - { src: 'p10k.zsh', dest: '.p10k.zsh' }
    - { src: 'usr/local/bin/compiler', dest: 'scripts/compiler' }
    - { src: 'usr/local/bin/opout', dest: 'scripts/opout' }
    - { src: 'scripts/rotate-screen', dest: 'scripts/rotate-screen' }
    - { src: 'scripts/wallpaper-engine', dest: 'scripts/wallpaper-engine' }
    - { src: 'scripts/switch-audio', dest: 'scripts/switch-audio' }
    - { src: 'scripts/decrease-volume', dest: 'scripts/decrease-volume' }
    - { src: 'scripts/increase-volume', dest: 'scripts/increase-volume' }
    - { src: 'scripts/toggle-spotify', dest: 'scripts/toggle-spotify' }
    - { src: 'scripts/project-finder', dest: 'scripts/project-finder' }
    - { src: 'scripts/project-terminals', dest: 'scripts/project-terminals' }
    - { src: 'pjx/project-terminals.txt', dest: 'pjx/project-terminals.txt' }

- name: system setup | Build st package
  become_user: quatro
  ansible.builtin.command: "makepkg -sfc"
  args:
    chdir: /home/quatro/scripts/archcraft/archcraft-st

- name: system setup | Build dwm package
  become_user: quatro
  ansible.builtin.command: "makepkg -sfc"
  args:
    chdir: /home/quatro/scripts/archcraft/archcraft-dwm

- name: system setup | Build and install dwm and st packages
  ansible.builtin.script:
    cmd: /home/quatro/scripts/archcraft/build-packages.sh

# - name: system setup | Install st package
#   become_user: quatro
#   community.general.pacman:
#     name:
#       - /home/quatro/scripts/archcraft/archcraft-st/archcraft-st-0.8.4-3-x86_64.pkg.tar.zst
#     state: present
#
# - name: system setup | Install dwm package
#   become_user: quatro
#   community.general.pacman:
#     name:
#       - /home/quatro/scripts/archcraft/archcraft-dwm/archcraft-dwm-2.0-0-any.pkg.tar.zst
#     state: present


# - name: users | quatro | checkout git repositories
#   tags: git,users,quatro
#   become: yes
#   git:
#     repo: "{{ item.repo }}"
#     dest: "{{ item.dest }}"
#     force: yes
#   with_items:
#     - { repo: 'https://github.com/ctrlpvim/ctrlp.vim.git', dest: '/home/quatro/.vim/bundle/ctrlp.vim' }
#     - { repo: 'https://github.com/davidhalter/jedi-vim.git', dest: '/home/quatro/.vim/bundle/jedi-vim' }
#     - { repo: 'https://github.com/pearofducks/ansible-vim', dest: '/home/quatro/.vim/bundle/ansible-vim' }
#     - { repo: 'https://github.com/rhysd/vim-grammarous.git', dest: '/home/quatro/.vim/bundle/vim-grammarous' }
#     - { repo: 'https://github.com/ron89/thesaurus_query.vim', dest: '/home/quatro/.vim/bundle/thesaurus_query' }
#     - { repo: 'https://github.com/scrooloose/nerdtree.git', dest: '/home/quatro/.vim/bundle/nerdtree' }
#     - { repo: 'https://github.com/tpope/vim-obsession.git', dest: '/home/quatro/.vim/bundle/vim-obsession' }
#     - { repo: 'https://github.com/vim-syntastic/syntastic.git', dest: '/home/quatro/.vim/bundle/syntastic' }
#   notify: update_vim_bundle_perms
