export ZSH=/usr/share/oh-my-zsh

zstyle ':omz:update' mode reminder  # disable automatic updates
zstyle ':omz:update' frequency 13

plugins=(git zsh-autosuggestions fast-syntax-highlighting)

source $ZSH/oh-my-zsh.sh
if [[ -n $SSH_CONNECTION ]]; then
    export EDITOR='nvim'
else
    export EDITOR='nvim'
fi
setopt autocd		# Automatically cd into typed directory.
stty stop undef		# Disable ctrl-s to freeze terminal.
setopt interactive_comments

# History in cache directory:
HISTSIZE=10000000
SAVEHIST=10000000
zshcache_time="$(date +%s%N)"

bindkey '^H' kill-word


bindkey -s '^o' '^ulf\n'
bindkey -s '^a' '^ubc -lq\n'
bindkey '^[[P' delete-char
bindkey -s '^f' '. project-finder\n'
bindkey -s '^p' 'project-terminals\n'


# autoload -Uz add-zsh-hook
#
# rehash_precmd() {
#     if [[ -a /var/cache/zsh/pacman ]]; then
#         local paccache_time="$(date -r /var/cache/zsh/pacman +%s%N)"
#         if (( zshcache_time < paccache_time )); then
#             rehash
#             zshcache_time="$paccache_time"
#         fi
#     fi
# }
#
# add-zsh-hook -Uz precmd rehash_precmd
# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# ls
alias l='ls -lh'
alias ll='ls -lah'
alias la='ls -A'
alias lm='ls -m'
alias lr='ls -R'
alias lg='ls -l --group-directories-first'

# git
alias gcl='git clone --depth 1'
alias gi='git init'
alias ga='git add'
alias gc='git commit -m'
alias gp='git push origin master'

alias nv='nvim'

# configs
alias autostart-config='sudo vim /usr/share/archcraft/dwm/bin/autostart.sh'
alias cdd='cd ~/scripts/archcraft'
alias cdq='cd qmk_firmware/keyboards/xiudi/xd75/keymaps/mugen'
alias cdn='cd ~/.config/nvim'
alias cx='chmod +x'


export PNPM_HOME="~/.local/share/pnpm"
export PATH="$PATH:$PNPM_HOME:~/.local/bin:/usr/.local/bin"

export DOTREPO="~/dotFiles"

alias dotdrop="$DOTREPO/dotdrop.sh"
alias dotgit="git -C $DOTREPO"
alias dotcd="cd $DOTREPO"
alias dotpush="dotgit pull && dotgit add -A && dotgit commit && dotgit push"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# pnpm
export PNPM_HOME="~/.local/share/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac
# pnpm end

source /usr/share/zsh-theme-powerlevel10k/powerlevel10k.zsh-theme

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
