volnorm = true
flip_status_indicators = true

[theme]
background = "#252525"
primary = "#D5D5D5"
secondary = "ABABAB"
title = "#d5d5d5"
playing = "#1db954"
playing_selected = "#E7D7FF"
playing_bg = "#151515"
highlight = "#76BFEB"
highlight_bg = "#000000"
error = "#f8f8f2"
error_bg = "#ff5555"
statusbar = "black"
statusbar_progress = "#bd93f9"
statusbar_bg = "#bd93f9"
cmdline = "#f8f8f2"
cmdline_bg = "black"
search_match = "#ff79c6"

## Base16 solarized dark, originally form https://github.com/gidsi/base16-ncspot
# [theme]
# background = "#002b36"
# primary = "#eee8d5"
# secondary = "#2aa198"
# title = "#859900"
# playing = "#268bd2"
# playing_selected = "light green"
# playing_bg = "#002b36"
# highlight = "#93a1a1"
# highlight_bg = "#484848"
# error = "#93a1a1"
# error_bg = "#fdf6e3"
# statusbar = "#002b36"
# statusbar_progress = "#dc322f"
# statusbar_bg = "#859900"
# cmdline = "#93a1a1"
# cmdline_bg = "#002b36"

## Spotify
# [theme]
# background = "black"
# primary = "light white"
# secondary = "light black"
# title = "green"
# playing = "green"
# playing_selected = "light green"
# playing_bg = "black"
# highlight = "light white"
# highlight_bg = "#484848"
# error = "light white"
# error_bg = "red"
# statusbar = "black"
# statusbar_progress = "green"
# statusbar_bg = "green"
# cmdline = "light white"
# cmdline_bg = "black"
