- name: system setup | upgrade all packages
  community.general.pacman:
    update_cache: true
    upgrade: true
  when: ansible_distribution == "Archlinux"

- name: system setup | install all packages part1 (pacman)
  tags: ansible,ansible-setup,packages
  community.general.pacman:
    name: 
      - archlinux-keyring
      - arandr
      - xorg-xinit
      - linux-zen
      - linux-zen-docs
      - linux-zen-headers
      - grub-customizer
      - python3
      - python-pip
      - go
      - mpv
      - flameshot
      - filezilla
      - playerctl
      - electron
      - ripgrep
      - fzf
      - picom
    state: latest
  when: ansible_distribution == "Archlinux"

- name: Check installed packages
  ansible.builtin.command: pacman -Qm
  register: installed_packages

- name: system setup | install all packages part2 (yay)
  tags: ansible,ansible-setup,packages
  become_user: quatro
  ansible.builtin.command: "yay --noconfirm --noprogressbar --needed --sync {{ item }}"
  when: item not in installed_packages.stdout and ansible_distribution == "Archlinux"
  with_items:
      - neovim-git
      - spotify
      - nerd-fonts-git
      - zsh-theme-powerlevel10k-git
      - python-launchpadlib
      - nvm
      - gotop-bin
      - ksuperkey
      - pam_ssh
      - beekeeper-studio-bin
      - discord_arch_electron
      - xmousepasteblock
      - shantz-xwinwrap-bzr
      - betterdiscord-installer
      - betterlockscreen

- name: Install st package
  community.general.pacman:
    name:
      - /home/quatro/scripts/archcraft/archcraft-st/archcraft-st-0.8.4-3-x86_64.pkg.tar.zst
    state: present

- name: Install dwm package
  community.general.pacman:
    name:
      - /home/quatro/scripts/archcraft/archcraft-dwm/archcraft-dwm-2.0-0-any.pkg.tar.zst
    state: present

