- name: system setup | upgrade all packages
  community.general.pacman:
    update_cache: true
    upgrade: true
  when: ansible_distribution == "Archlinux"

- name: system setup | install all packages part1 (pacman)
  tags: ansible,ansible-setup,packages
  community.general.pacman:
    name: 
      - archlinux-keyring
      - arandr
      - xorg-xinit
      - linux-zen
      - linux-zen-docs
      - linux-zen-headers
      - grub-customizer
      - python3
      - python-pip
      - go
      - mpv
      - flameshot
      - filezilla
      - playerctl
      - electron
      - ripgrep
      - fzf
      - zsh
      - zsh-completions
      - picom
    state: latest
  when: ansible_distribution == "Archlinux"

- name: Check installed packages
  ansible.builtin.command: pacman -Qm
  register: installed_packages

- name: system setup | install all packages part2 (yay)
  tags: ansible,ansible-setup,packages
  become: yes
  become_user: aur_builder
  kewlfft.aur.aur:
    use: yay
    name:
      - lib32-ncurses-git
      - ncurses-git
      - neovim-git
      - ncspot
      - oh-my-zsh-git
      - zsh-theme-powerlevel10k-git
      - python-launchpadlib
      - nvm
      - gotop-bin
      - ksuperkey
      - pam_ssh
      - beekeeper-studio-bin
      - discord_arch_electron
      - xmousepasteblock
      - shantz-xwinwrap-bzr
      - betterdiscord-installer
      - betterlockscreen
      - nerd-fonts-git
  when: ansible_distribution == "Archlinux"


