- name: system setup | upgrade all packages
  community.general.pacman:
    update_cache: true
    upgrade: true
  when: ansible_distribution == "Archlinux"

- name: system setup | install all packages part1 (pacman)
  tags: ansible,ansible-setup,packages
  community.general.pacman:
    name: 
      - archlinux-keyring
      - arandr
      - linux-zen
      - linux-zen-docs
      - linux-zen-headers
      - grub-customizer
      - python3
      - python-pip
      - go
      - mpv
      - flameshot
      - filezilla
      - playerctl
      - electron
      - ripgrep
      - fzf
      - luarocks
      - zip
      - unzip
      - jdk-openjdk
      - man-db
      - man-pages
      - less
      - texinfo
      - lxappearance
      - pavucontrol
      - fastfetch
      - openssh
      - vi
      - strace
      - udiskie
      - wl-clipboard
      - yazi 
      - ffmpegthumbnailer 
      - unarchiver 
      - jq
      - poppler
      - fd
      - zoxide
    state: latest
  when: ansible_distribution == "Archlinux"
- name: Check installed packages
  ansible.builtin.command: pacman -Qm
  register: installed_packages

- name: system setup | install all packages part2 (yay)
  tags: ansible,ansible-setup,packages
  kewlfft.aur.aur:
    use: yay
    state: present
    name:
      - neovim-git
      - ncspot
      - nvm
      - gotop-bin
      - beekeeper-studio-bin
      - discord_arch_electron
      - betterdiscord-installer
      - hyprland-git
      - kitty
      - waybar
      - swaybg
      - swaylock-effects
      - wofi
      - wlogout
      - mako
      - thunar
      - ttf-jetbrains-mono-nerd
      - noto-fonts-emoji
      - polkit-gnome
      - python-requests
      - starship
      - swappy
      - grim
      - slurp
      - pamixer
      - brightnessctl
      - gvfs
      - bluez
      - bluez-utils
      - nwg-look-bin
      - xfce4-settings
      - dracula-gtk-theme
      - dracula-icons-git
      - xdg-desktop-portal-hyprland
      - mpvpaper-git
      - noto-fonts
      - brave-bin
      - bibata-cursor-theme
      - pam_ssh
      - hyprpicker-git
      - otf-ibm-plex
      - wofi-emoji
      - lazygit-git
  become: yes
  become_user: aur_builder

- name: Create terminal symbolic link for Gnome Gio / wofi
  ansible.builtin.file:
    src: '/usr/bin/kitty'
    dest: '/usr/bin/gnome-terminal'
    owner: quatro
    group: quatro
    state: link
